const strings={
     CurrentPassword : "Current Password",
     NewPassword : "New Password",
     ConfirmPassword : "Confirm Password",
     EnterCurrentPassword : "Enter Current Password",
     EnterNewPassword : " Enter New Password",
     EnterConfirmPassword : "Enter Confirm Password",
     submit : "Submit",
     cancel: "Cancel",
     changePassword: "Change Password",
     Dashboard: "Dashboard",
     LeaveRequest: "Leave Request",
     NoOfDays: "No of Days",
     DaysApplied: "Days Applied",
     From: "From",
     To: "To",
     Reason: "Reason",
     MyRequests: "My Requests",
     Pending: "Pending",
     Approved: "Approved",
     Rejected: "Rejected",
     Balance: "Balance",
     Approvals: "Approvals",
     ForgotUserID :"Forgot User ID/Password?",
     EmailAddress: "Email Address",
     Holidays: "Holidays",
     India: "India",
     Dallas: "Dallas",
     All: "All",
     Open: "Open",
     Cancelled: "Cancelled",
     Status: "Status",
     EmployeeName: "Employee Name",
     DateCreated: "Date Created",
     Filter: "Filter",
     Sort: "Sort",
     NoLeave: "No Leave For Approval",
     NoLeaveRequest: "No Leave Request",
     Password: "Password",
     MyProfile: "My Profile",
     Settings: "Settings",
     Used: "Used:",
     Remaining: "Remaining:",
     RequestedBy: "Requested By:",
     RequestSentTo: "Request Sent To:",
     


 }
export default strings;